# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
