# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170124_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='article_download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_file_path', models.CharField(max_length=500)),
                ('article_download_created_date', models.DateField()),
                ('article_download_last_updated', models.DateField()),
                ('iss_parsed', models.TextField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='article_parsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('published_date', models.DateField()),
                ('created_date', models.DateField()),
                ('unique_id', models.CharField(max_length=250)),
                ('Source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.source')),
                ('article_download_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article_download')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author')),
                ('unresolved_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.unresolved_location')),
                ('uresolved_news_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.unresolved_news_type')),
            ],
        ),
        migrations.AlterField(
            model_name='map_unresolved_resolved_location',
            name='unresolved_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.unresolved_location', unique=True),
        ),
        migrations.AlterField(
            model_name='map_unresolved_resolved_news_type_map',
            name='unresolved_news_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.unresolved_news_type', unique=True),
        ),
        migrations.AlterField(
            model_name='resolved_location',
            name='resolved_location_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='resolved_news_type',
            name='resolved_news_type_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='article_content',
            name='article_parsed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article_parsed'),
        ),
    ]
