# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170124_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_download',
            name='article_download_created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='article_download',
            name='article_download_last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='article_parsed',
            name='created_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='article_parsed',
            name='published_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='article_parsed',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
